// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOyBuyaCJWcYtKCVRBayd8s96NrIdTn8E',
    appId: '1:773944575382:android:42f566e8116b8dd05bc9b7',
    messagingSenderId: '773944575382',
    projectId: 'otobus-db-5d98e',
    databaseURL: 'https://otobus-db-5d98e-default-rtdb.firebaseio.com',
    storageBucket: 'otobus-db-5d98e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXZvSpXorV2I6T6Zw54HlIQSkWK23D1VA',
    appId: '1:773944575382:ios:5149e0e67ff4ad225bc9b7',
    messagingSenderId: '773944575382',
    projectId: 'otobus-db-5d98e',
    databaseURL: 'https://otobus-db-5d98e-default-rtdb.firebaseio.com',
    storageBucket: 'otobus-db-5d98e.firebasestorage.app',
    iosBundleId: 'com.example.otobusApp',
  );
}
